data_type: keyphrase

train_src: data/keyphrase/meng17/kp20k/kp20k_train.src
train_tgt: data/keyphrase/meng17/kp20k/kp20k_train.tgt
valid_src: data/keyphrase/meng17/kp20k/kp20k_valid.src
valid_tgt: data/keyphrase/meng17/kp20k/kp20k_valid.tgt

save_data: data/keyphrase/meng17/kp20k_pt_shard10k/
shard_size: 10000
dynamic_dict: 'true'
share_vocab: 'true'

src_vocab: data/keyphrase/meng17/magkp20k.vocab.pt # use the pre-generated vocab
src_seq_length_trunc: 512
tgt_seq_length_trunc: 8
lower: 'true'
filter_valid: 'false'

report_every: 1000
log_file: data/keyphrase/meng17/preprocess.kp20k_shard10k.log

