#train_from: /zfs1/hdaqing/rum20/kp/fairseq-kpg/exps/kp/transformer_presabs_kp20k/ckpts/checkpoint_step_135000.pt

### Exp meta
exp: transformer-presabs-kp20k-OR001-SC001
exp_dir: /zfs1/pbrusilovsky/rum20/kp/diverse_exps/transformer-presabs-kp20k-OR001-SC001
save_model: /zfs1/pbrusilovsky/rum20/kp/diverse_exps/transformer-presabs-kp20k-OR001-SC001/ckpts/checkpoint
log_file: /zfs1/pbrusilovsky/rum20/kp/diverse_exps/transformer-presabs-kp20k-OR001-SC001/log.txt
wandb_project: transfer_kp

### KP parameters
target_encoder_layers: 3
num_negsample: 16
detach_target_encoder: 'true'
orth_reg: 'true'
lambda_orth_reg: 0.01
sem_cov: 'true'
lambda_sem_cov: 0.01
use_ending_state: 'true'

### Data opts:
model_task: seq2seq
data_type: keyphrase
data_format: jsonl

src_seq_length_trunc: 512
tgt_seq_length_trunc: 128
shuffle_shards: false
data:
    corpus_1:
        path_src: /zfs1/hdaqing/rum20/kp/data/kp/json/kp20k/train.json
        type: keyphrase
        transforms: [keyphrase, onmt_tokenize]
#        transforms: [keyphrase, roberta_tokenize_kpg]

### Transform related opts:
#### Keyphrase specific
kp_concat_type: pres_abs
max_target_phrases: 8

share_vocab: True
#### Word and vocab
src_vocab: /zfs1/pbrusilovsky/rum20/kp/OpenNMT-kpg/data/keyphrase/meng17/magkp20k.vocab.json
src_vocab_size: 50000
lowercase: True
return_tokens: True
keep_punctuations: True
add_src_boseos: False

#### Subword and vocab
#src_subword_model: roberta_tokenize
#src_vocab: /zfs1/hdaqing/rum20/kp/data/kp/hf_vocab/roberta-base-kp/vocab.json
#bpe_dropout: 0.0

#### Sampling
switchout_temperature: 1.0
tokendrop_temperature: 1.0
tokenmask_temperature: 1.0
#### Filter, default is 1024
src_seq_length: -1
tgt_seq_length: -1
#### BART
permute_sent_ratio: 0.0
rotate_ratio: 0.0
insert_ratio: 0.0
random_ratio: 0.0
mask_ratio: 0.0
mask_length: subword
poisson_lambda: 3.0
replace_length: 1

# Model opts:
encoder_type: transformer
decoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 6
heads: 8
dropout: 0.1

share_embeddings: 'true'
copy_attn: 'true'
reuse_copy_attn: 'true'
coverage_attn: 'false'
context_gate: both
input_feed: 1
param_init_glorot: 'true'
position_encoding: 'true'

optim: adam
learning_rate: 3e-4
warmup_steps: 10000
decay_method: linear
label_smoothing: 0.1
adam_beta2: 0.998
max_grad_norm: 2.0

batch_size: 16
accum_count: 4
valid_batch_size: 64
max_generator_batches: 200

batch_type: sents
normalization: sents

train_steps: 100000
valid_steps: 10000
save_checkpoint_steps: 5000
report_every: 100
seed: 3435

log_file_level: DEBUG
tensorboard: 'false'

#tensorboard_log_dir: runs/kp20k.one2one.transformer/

wandb: 'false'
wandb_key: 'c338136c195ab221b8c7cfaa446db16b2e86c6db'


world_size: 1
gpu_ranks:
- 0
#- 1
#- 2
#master_port: 10000